//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRealtyWeb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainTemplatesHtml
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MainTemplatesHtml()
        {
            this.ClientTemplates = new HashSet<ClientTemplate>();
        }
    
        public int TemplateMasterID { get; set; }
        public string TemplateName { get; set; }
        public string Description { get; set; }
        public string Features { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ImageUrl { get; set; }
        public string LogoUrl { get; set; }
        public string DomainUrl { get; set; }
        public Nullable<int> FreeTrailDays { get; set; }
        public Nullable<decimal> MonthlyPrice { get; set; }
        public string TemplateType { get; set; }
        public Nullable<int> TemplateCategoryID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientTemplate> ClientTemplates { get; set; }
        public virtual TemplateCategory TemplateCategory { get; set; }
    }
}
