//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRealtyWeb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TemplateCategory()
        {
            this.MainTemplatesHtmls = new HashSet<MainTemplatesHtml>();
        }
    
        public int TemplateCategoryId { get; set; }
        public string TemplateCategoryName { get; set; }
        public Nullable<int> FreeTrailDays { get; set; }
        public Nullable<decimal> MonthlyPrice { get; set; }
        public Nullable<decimal> SetupFee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainTemplatesHtml> MainTemplatesHtmls { get; set; }
    }
}
